#!/bin/bash

## declare an array variable
## declare -a laravel=("5.5.*" "5.6.*" "5.7.*" "5.8.*" "6.*" "7.*")
## declare -a testbench=("3.5.*" "3.6.*" "3.7.*" "3.8.*" "4.*" "5.*")
##
## for i in "${!laravel[@]}"
## do
##    echo "${laravel[i]}"
##    echo "${testbench[i]}"
##
##    composer remove --quiet illuminate/support orchestra/testbench
##    composer require --no-update --no-interaction --quiet "illuminate/support:${laravel[i]}" "orchestra/testbench:${testbench[i]}"
##    composer update --prefer-dist --no-interaction --quiet
##    ./vendor/bin/phpunit
## done


composer remove --quiet illuminate/support orchestra/testbench \
&& composer require --no-update --no-interaction --quiet "illuminate/support:7" "orchestra/testbench:5" \
&& composer update --prefer-lowest --prefer-dist --no-interaction \
&& ./vendor/bin/phpunit